### ISSUE TITLE
Can't convert csv/txt file back to msg format

### ISSUE THREAD

**Issue by A2CJB** [dtlnor/REMSG_Converter#1]
So I'm able to convert the .msg* file to a csv or a txt file but I can't seem to convert it back to the msg format. Dragging and dropping the file onto the chosen bat file just says 'No valid input file' and closes the window. Am I missing something?

**Comment by dtlnor** [comment]
you should highlight both original msg and your modified file. Otherwise converter don't know which msg version you are converting to.
