### ISSUE TITLE
Can't convert csv/txt file back to msg format 

### ISSUE THREAD

**Issue by xjgames** [dtlnor/REMSG_Converter#2]
RE4R

**Comment by xjgames** [comment]
ch_ mes_ main_ sys_ common.msg.22
Abnormal text display in the game

**Comment by dtlnor** [comment]
ummm can you elaborate more?

**Comment by xjgames** [comment]
Can you add the function of bulk importing text?

**Comment by dtlnor** [comment]
> Can you add the function of bulk importing text?

actually it could, by drag and drop folder

**Comment by xjgames** [comment]
Can export text files in bulk, but cannot import text in bulk

**Comment by dtlnor** [comment]
> Can export text files in bulk, but cannot import text in bulk

try to group your text file into one folder, and msg file into another. then drag two folder into bat

**Comment by xjgames** [comment]
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csa144.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csa145.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csa147.msg.22
DEBUG:chardet.charsetprober:EUC-JP Japanese prober hit error at byte 19
DEBUG:chardet.charsetprober:EUC-KR Korean prober hit error at byte 19
DEBUG:chardet.charsetprober:CP949 Korean prober hit error at byte 19
DEBUG:chardet.charsetprober:EUC-TW Taiwan prober hit error at byte 19
DEBUG:chardet.charsetprober:Johab Korean prober hit error at byte 19
DEBUG:chardet.charsetprober:utf-8  confidence = 0.938125
DEBUG:chardet.charsetprober:SHIFT_JIS Japanese confidence = 0.01
DEBUG:chardet.charsetprober:EUC-JP Japanese prober hit error at byte 19
DEBUG:chardet.charsetprober:EUC-JP not active
DEBUG:chardet.charsetprober:EUC-JP Japanese prober hit error at byte 19
DEBUG:chardet.charsetprober:EUC-KR Korean prober hit error at byte 19
DEBUG:chardet.charsetprober:GB2312 Chinese confidence = 0.01
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csa149.msg.22
DEBUG:chardet.charsetprober:EUC-KR Korean prober hit error at byte 19
DEBUG:chardet.charsetprober:CP949 Korean prober hit error at byte 19
DEBUG:chardet.charsetprober:EUC-KR not active
DEBUG:chardet.charsetprober:CP949 Korean prober hit error at byte 19
DEBUG:chardet.charsetprober:EUC-TW Taiwan prober hit error at byte 19
DEBUG:chardet.charsetprober:CP949 not active
DEBUG:chardet.charsetprober:EUC-TW Taiwan prober hit error at byte 19
DEBUG:chardet.charsetprober:Johab Korean prober hit error at byte 19
DEBUG:chardet.charsetprober:Big5 Chinese confidence = 0.01
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csa150.msg.22
DEBUG:chardet.charsetprober:Johab Korean prober hit error at byte 19
DEBUG:chardet.charsetprober:utf-8  confidence = 0.938125
DEBUG:chardet.charsetprober:EUC-TW not active
DEBUG:chardet.charsetprober:utf-8  confidence = 0.938125
DEBUG:chardet.charsetprober:SHIFT_JIS Japanese confidence = 0.01
DEBUG:chardet.charsetprober:Johab not active
DEBUG:chardet.charsetprober:SHIFT_JIS Japanese confidence = 0.01
DEBUG:chardet.charsetprober:SHIFT_JIS Japanese prober hit error at byte 26
DEBUG:chardet.charsetprober:EUC-JP not active
DEBUG:chardet.charsetprober:windows-1251 Russian confidence = 0.01
DEBUG:chardet.charsetprober:EUC-JP not active
DEBUG:chardet.charsetprober:EUC-JP Japanese prober hit error at byte 23
DEBUG:chardet.charsetprober:GB2312 Chinese confidence = 0.01
DEBUG:chardet.charsetprober:KOI8-R Russian confidence = 0.01
DEBUG:chardet.charsetprober:GB2312 Chinese confidence = 0.01
DEBUG:chardet.charsetprober:EUC-KR Korean prober hit error at byte 23
DEBUG:chardet.charsetprober:EUC-KR not active
DEBUG:chardet.charsetprober:ISO-8859-5 Russian confidence = 0.01
DEBUG:chardet.charsetprober:EUC-KR not active
DEBUG:chardet.charsetprober:CP949 Korean prober hit error at byte 23
DEBUG:chardet.charsetprober:CP949 not active
DEBUG:chardet.charsetprober:MacCyrillic Russian confidence = 0.01
DEBUG:chardet.charsetprober:CP949 not active
DEBUG:chardet.charsetprober:EUC-TW Taiwan prober hit error at byte 23
DEBUG:chardet.charsetprober:Big5 Chinese confidence = 0.01
DEBUG:chardet.charsetprober:IBM866 Russian confidence = 0.01
DEBUG:chardet.charsetprober:Big5 Chinese confidence = 0.01
DEBUG:chardet.charsetprober:Johab Korean prober hit error at byte 18
DEBUG:chardet.charsetprober:EUC-TW not active
DEBUG:chardet.charsetprober:IBM855 Russian confidence = 0.01
DEBUG:chardet.charsetprober:EUC-TW not active
DEBUG:chardet.charsetprober:utf-8  confidence = 0.938125
DEBUG:chardet.charsetprober:Johab not active
DEBUG:chardet.charsetprober:ISO-8859-7 Greek confidence = 0.01
DEBUG:chardet.charsetprober:Johab not active
DEBUG:chardet.charsetprober:SHIFT_JIS not active
DEBUG:chardet.charsetprober:windows-1251 Russian confidence = 0.01
DEBUG:chardet.charsetprober:windows-1253 Greek confidence = 0.01
DEBUG:chardet.charsetprober:windows-1251 Russian confidence = 0.01
DEBUG:chardet.charsetprober:EUC-JP not active
DEBUG:chardet.charsetprober:KOI8-R Russian confidence = 0.01
DEBUG:chardet.charsetprober:ISO-8859-5 Bulgarian confidence = 0.01
DEBUG:chardet.charsetprober:KOI8-R Russian confidence = 0.01
DEBUG:chardet.charsetprober:GB2312 Chinese confidence = 0.01
DEBUG:chardet.charsetprober:ISO-8859-5 Russian confidence = 0.01
DEBUG:chardet.charsetprober:windows-1251 Bulgarian confidence = 0.01
DEBUG:chardet.charsetprober:ISO-8859-5 Russian confidence = 0.01
DEBUG:chardet.charsetprober:EUC-KR not active
DEBUG:chardet.charsetprober:MacCyrillic Russian confidence = 0.01
DEBUG:chardet.charsetprober:TIS-620 Thai confidence = 0.01
DEBUG:chardet.charsetprober:MacCyrillic Russian confidence = 0.01
DEBUG:chardet.charsetprober:CP949 not active
DEBUG:chardet.charsetprober:IBM866 Russian confidence = 0.01
DEBUG:chardet.charsetprober:ISO-8859-9 Turkish confidence = 0.01
DEBUG:chardet.charsetprober:IBM866 Russian confidence = 0.01
DEBUG:chardet.charsetprober:Big5 Chinese confidence = 0.01
DEBUG:chardet.charsetprober:IBM855 Russian confidence = 0.01
DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.0
DEBUG:chardet.charsetprober:IBM855 Russian confidence = 0.01
DEBUG:chardet.charsetprober:EUC-TW not active
DEBUG:chardet.charsetprober:ISO-8859-7 Greek confidence = 0.01
DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.01
DEBUG:chardet.charsetprober:ISO-8859-7 Greek confidence = 0.01
DEBUG:chardet.charsetprober:Johab not active
DEBUG:chardet.charsetprober:windows-1253 Greek confidence = 0.01
DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.01
DEBUG:chardet.charsetprober:windows-1253 Greek confidence = 0.01
DEBUG:chardet.charsetprober:windows-1251 Russian confidence = 0.01
DEBUG:chardet.charsetprober:ISO-8859-5 Bulgarian confidence = 0.01
DEBUG:chardet.charsetprober:utf-8  confidence = 0.938125
DEBUG:chardet.charsetprober:ISO-8859-5 Bulgarian confidence = 0.01
DEBUG:chardet.charsetprober:KOI8-R Russian confidence = 0.01
DEBUG:chardet.charsetprober:windows-1251 Bulgarian confidence = 0.01
DEBUG:chardet.charsetprober:SHIFT_JIS Japanese confidence = 0.01
DEBUG:chardet.charsetprober:windows-1251 Bulgarian confidence = 0.01
DEBUG:chardet.charsetprober:ISO-8859-5 Russian confidence = 0.0
DEBUG:chardet.charsetprober:TIS-620 Thai confidence = 0.01
DEBUG:chardet.charsetprober:EUC-JP not active
DEBUG:chardet.charsetprober:TIS-620 Thai confidence = 0.01
DEBUG:chardet.charsetprober:MacCyrillic Russian confidence = 0.01
DEBUG:chardet.charsetprober:ISO-8859-9 Turkish confidence = 0.01
DEBUG:chardet.charsetprober:GB2312 Chinese confidence = 0.01
DEBUG:chardet.charsetprober:ISO-8859-9 Turkish confidence = 0.01
DEBUG:chardet.charsetprober:IBM866 Russian confidence = 0.01
DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.0
DEBUG:chardet.charsetprober:EUC-KR not active
DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.0
DEBUG:chardet.charsetprober:IBM855 Russian confidence = 0.0
DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.01
DEBUG:chardet.charsetprober:CP949 not active
DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.01
DEBUG:chardet.charsetprober:ISO-8859-7 Greek confidence = 0.01
DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.01
DEBUG:chardet.charsetprober:Big5 Chinese confidence = 0.01
DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.01
DEBUG:chardet.charsetprober:windows-1253 Greek confidence = 0.01
DEBUG:chardet.charsetprober:utf-8  confidence = 0.938125
DEBUG:chardet.charsetprober:EUC-TW not active
DEBUG:chardet.charsetprober:utf-8  confidence = 0.938125
DEBUG:chardet.charsetprober:ISO-8859-5 Bulgarian confidence = 0.0
DEBUG:chardet.charsetprober:SHIFT_JIS Japanese confidence = 0.01
DEBUG:chardet.charsetprober:Johab not active
DEBUG:chardet.charsetprober:SHIFT_JIS Japanese confidence = 0.01
DEBUG:chardet.charsetprober:windows-1251 Bulgarian confidence = 0.01
DEBUG:chardet.charsetprober:EUC-JP not active
DEBUG:chardet.charsetprober:EUC-JP not active
DEBUG:chardet.charsetprober:TIS-620 Thai confidence = 0.30359914765551294
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csa153.msg.22
DEBUG:chardet.charsetprober:GB2312 Chinese confidence = 0.01
DEBUG:chardet.charsetprober:GB2312 Chinese confidence = 0.01
DEBUG:chardet.charsetprober:ISO-8859-9 Turkish confidence = 0.01
DEBUG:chardet.charsetprober:EUC-KR not active
DEBUG:chardet.charsetprober:EUC-KR not active
DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.0
DEBUG:chardet.charsetprober:CP949 not active
DEBUG:chardet.charsetprober:CP949 not active
DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.01
DEBUG:chardet.charsetprober:Big5 Chinese confidence = 0.01
DEBUG:chardet.charsetprober:Big5 Chinese confidence = 0.01
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csa154.msg.22
DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.01
DEBUG:chardet.charsetprober:EUC-TW not active
DEBUG:chardet.charsetprober:EUC-TW not active
DEBUG:chardet.charsetprober:utf-8  confidence = 0.938125
DEBUG:chardet.charsetprober:Johab not active
DEBUG:chardet.charsetprober:Johab not active
DEBUG:chardet.charsetprober:SHIFT_JIS not active
DEBUG:chardet.charsetprober:EUC-JP not active
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csa155.msg.22
DEBUG:chardet.charsetprober:GB2312 Chinese confidence = 0.01
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csa156.msg.22
DEBUG:chardet.charsetprober:EUC-KR not active
DEBUG:chardet.charsetprober:CP949 not active
DEBUG:chardet.charsetprober:Big5 Chinese confidence = 0.01
DEBUG:chardet.charsetprober:EUC-TW not active
DEBUG:chardet.charsetprober:Johab not active
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csa157.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csa158.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csa159.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb100.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb101.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb104.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb106.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb107.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb110.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb111.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb112.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb115.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb116.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb117.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb118.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb119.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb128.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb129.msg.22
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb130.msg.22
DEBUG:chardet.charsetprober:Johab Korean prober hit error at byte 18
DEBUG:chardet.charsetprober:utf-8  confidence = 0.87625
DEBUG:chardet.charsetprober:SHIFT_JIS Japanese confidence = 0.01
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb131.msg.22
DEBUG:chardet.charsetprober:EUC-JP Japanese confidence = 0.01
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_csb135.msg.22
DEBUG:chardet.charsetprober:GB2312 Chinese confidence = 0.01
DEBUG:chardet.charsetprober:EUC-KR Korean confidence = 0.01
DEBUG:chardet.charsetprober:CP949 Korean confidence = 0.01
DEBUG:chardet.charsetprober:Big5 Chinese confidence = 0.01
DEBUG:chardet.charsetprober:EUC-TW Taiwan confidence = 0.01
DEBUG:chardet.charsetprober:Johab not active
DEBUG:chardet.charsetprober:windows-1251 Russian confidence = 0.01
processing:C:\Users\Administrator.DESKTOP-TBKU5F5\Desktop\yegi-dabao-msg\msg\ch_mes_main_mva000.msg.22
DEBUG:chardet.charsetprober:KOI8-R Russian confidence = 0.01
DEBUG:chardet.charsetprober:ISO-8859-5 Russian confidence = 0.01
DEBUG:chardet.charsetprober:MacCyrillic Russian confidence = 0.01
DEBUG:chardet.charsetprober:IBM866 Russian confidence = 0.01
DEBUG:chardet.charsetprober:IBM855 Russian confidence = 0.0
DEBUG:chardet.charsetprober:ISO-8859-7 Greek confidence = 0.01
DEBUG:chardet.charsetprober:windows-1253 Greek confidence = 0.01
DEBUG:chardet.charsetprober:ISO-8859-5 Bulgarian confidence = 0.01
DEBUG:chardet.charsetprober:windows-1251 Bulgarian confidence = 0.01
DEBUG:chardet.charsetprober:TIS-620 Thai confidence = 0.2698659090271226
DEBUG:chardet.charsetprober:ISO-8859-9 Turkish confidence = 0.01
DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.0
DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.01
DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.01
DEBUG:chardet.charsetprober:utf-8  confidence = 0.87625
DEBUG:chardet.charsetprober:SHIFT_JIS Japanese confidence = 0.01
DEBUG:chardet.charsetprober:EUC-JP Japanese confidence = 0.01
DEBUG:chardet.charsetprober:GB2312 Chinese confidence = 0.01
DEBUG:chardet.charsetprober:EUC-KR Korean confidence = 0.01
DEBUG:chardet.charsetprober:CP949 Korean confidence = 0.01
DEBUG:chardet.charsetprober:Big5 Chinese confidence = 0.01
DEBUG:chardet.charsetprober:EUC-TW Taiwan confidence = 0.01
DEBUG:chardet.charsetprober:Johab not active

**Comment by xjgames** [comment]
Is this prompt normal?

**Comment by dtlnor** [comment]
> Is this prompt normal?

yeah... its fine, just a bit annoying, those are debug log output

**Comment by dtlnor** [comment]
remove debug log output at https://github.com/dtlnor/REMSG_Converter/releases/tag/1.1.1

**Comment by xjgames** [comment]
Does it support DLC message files

**Comment by dtlnor** [comment]
> Does it support DLC message files

if its .msg file, it suppose to support.
