### ISSUE TITLE
[Enhancement] Release without pyinstaller

### ISSUE THREAD

**Issue by matyalatte** [dtlnor/REMSG_Converter#3]
Hi, I'm using this great tool for text modding.
But I want to use your scripts with portable python environment.
So, I made a branch can make a release package without pyinstaller.
https://github.com/matyalatte/REMSG_Converter/tree/no_compile

In the branch,
~~download_python_embeddable.bat~~
[download_portable_python.bat](https://github.com/matyalatte/REMSG_Converter/blob/no_compile/download_portable_python.bat) will put portable python in your repo.
Then, you can run the scripts like `python\python.exe src\main.py ...`

~~build.bat~~
[build_with_portable_python.bat](https://github.com/matyalatte/REMSG_Converter/blob/no_compile/build_with_portable_python.bat) will make a zip from your repo.
You can upload the zip to the release page as it is.

Here is a zip file made from the branch.
[REMSG_Converter_no_compile.zip](https://github.com/dtlnor/REMSG_Converter/files/11353806/REMSG_Converter_no_compile.zip)
It's smaller, faster, and safer than compiled exe.
Also, it's easy for end-users to edit codes!

I'll send PR if you like it.

**Comment by dtlnor** [comment]
~~If any one wants to edit my code that means they known Python and installed Python so they can manually clone or download my code then `py main.py` directly~~
It would be great to be a optional choice, I think I will keep both version on release page (exe some how more user friendly ~~although user friendly is nothing when doing a mod~~). Please send a PR and I will merge it.
