### ISSUE TITLE
Can you ADD for Support new Format for Resident Evil Village

### ISSUE THREAD

**Issue by muslimcyber26** [dtlnor/REMSG_Converter#7]
Hello. Can you make support the new format files for MSG RE Village ( *.msg.33685777 )

Tools can export the files. But, can't import the exported files to MSG

After tried the import, tools give me error notification: " No valid input file, exiting. 

I attach the new files from RE Village 

[REVillage.NewFormatMSG.June2023Update.zip](https://github.com/dtlnor/REMSG_Converter/files/13339553/REVillage.NewFormatMSG.June2023Update.zip)

**Comment by dtlnor** [comment]
It should support *.msg.33685777. By `No valid input file, exiting.` It means that the program did not found any file with `.msg.{number}`. you could remove the `.new` suffix from your modded file to let it work.

**Comment by dtlnor** [comment]
allow `.new` suffix as input at 1.1.2
