### ISSUE TITLE
I drag csv and msg to csv+msg2msg.bat, some thing doesn't right

### ISSUE THREAD

**Issue by MotokaJuu** [dtlnor/REMSG_Converter#8]
AttributeError: 'MSG' object has no attribute 'writeREMSG'
This error came out when I did that, and I got a 0kb file named 'CH_Mes_Main_Item_Caption.msg.22.new'

**Comment by MotokaJuu** [comment]
my fault

**Comment by dtlnor** [comment]
If you are using the latested python code, ~~yes its untested~~.
I've fixed some bugs, try it again if you want still want to run it directly

**Comment by MotokaJuu** [comment]
yes, the latested one is good. itd done the job
