### ISSUE TITLE
Dead Rising Deluxe Remaster .msg.23 file

### ISSUE THREAD

**Issue by Narayanna** [dtlnor/REMSG_Converter#9]
Hello, can you update the tool for Dead Rising Deluxe Remaster?
The tool doesn't work in the language file of this game. I uploaded some sample files.

https://gofile.io/d/vO0qLr

**Comment by dtlnor** [comment]
https://github.com/dtlnor/REMSG_Converter/releases/tag/1.2.0 try this

**Comment by Narayanna** [comment]
Yeah, that worked. Thank you very much.
And thank you for making such beautiful tools.
